config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root 'categories#index'

	resources :categories do
		resources :subcategories
	end

	resources :listings do
		collection do
			get 'search'
		end
	end
	

	match '/help', to: 'pages#help', via: :get
	match '/mylistings', to: 'listings#mylistings', via: :get
	match '/subcategories/find_by_category', to: 'subcategories#find_by_category', via: :post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :subcategories
	has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :category
	belongs_to :subcategory
	belongs_to :user
	
	validates :user_id, presence: true
	validates :title, :description, :city, :state, :zipcode, :category_id, :subcategory_id, presence: true

	geocoded_by :full_address
	after_validation :geocode

	def full_address
		[city, state, zipcode].join(', ')
	end


	def self.search(params)
		listings = Listing.where(category_id: params[:category].to_i)
		listings = listings.where("title like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
		listings = listings.near(params[:location], 20) if params[:location].present?
		listings
	end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
	belongs_to :category
	has_many :listings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception

	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
		@listings = Listing.where(category_id: params[:id]).order("created_at DESC")
	end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :find_list, only: [:show, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: [:show, :search]

	def show
		@sub = @listing.subcategory
	end

	def new
		@listing = current_user.listings.build
	end

	def create
		@listing = current_user.listings.build(list_params)

		if @listing.save
			redirect_to @listing
			flash[:notice] = "Post successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@listing.update(list_params)
		redirect_to @listing
	end

	def destroy
		@listing.destroy
		redirect_to mylistings_path
		flash[:notice] = "Post has been deleted"
	end

	def search
		@listings = Listing.search(params)
	end

	def mylistings
		@listings = Listing.where(user: current_user)
	end


	private

	def list_params
		params.require(:listing).permit(:title, :description, :city, :state, :zipcode, :category_id, :subcategory_id)
	end

	def find_list
		@listing = Listing.find(params[:id])
	end

	def correct_user
      	@listing = Listing.find(params[:id])

      	unless current_user == @listing.user
      		redirect_to root_path, alert: "You're not authorized to edit this post"
      	end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def help
	end
	
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

	def show
		@listings = Listing.where(subcategory_id: params[:id]).order("created_at DESC")
		@sub = Subcategory.find(params[:id])
	end

	def find_by_category
		category = Category.find(params[:category_id])
		subcategories = category.subcategories.find_all
		render json: { subcategories: subcategories}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/index.html.haml
%div.well
	%h4 Search rubylist
	= form_tag search_listings_path, class: 'form-inline', method: :get do |f|
		%div.form-group
			= text_field_tag :search, nil, placeholder: 'search', class: "form-control"
		%div.form-group
			= text_field_tag :location, nil, placeholder: 'near', class: "form-control"
		%div.form-group
			= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id ]}), class: "form-control"
		%div.form-group
			= submit_tag '>', class: 'btn btn-default'

%div.row
	- @categories.each do |cat|
		%div.col-md-4
			%div.panel.panel-default
				%div.panel-heading
					%h3.panel-title
						= link_to cat.name, category_path(cat)
						%span.label.label-primary
							= cat.listings.count
				%div.panel-body
					%ul
						- cat.subcategories.each do |sub|
							%li
								= link_to sub.name, category_subcategory_path(cat, sub)
								%span.label.label-default
									= sub.listings.count

app/views/categories/show.html.haml
%ol.breadcrumb
	%li= link_to "Rubylist", root_path
	%li= @category.name

%div.btn-group
	- @category.subcategories.each do |sub|
		%div.btn.btn-default
			= link_to sub.name, category_subcategory_path(@category, sub)
%br
%br
- if @listings.present?
	- @listings.each do |listing|
		%div
			%div.col-xs-3
				= listing.created_at.strftime('%d %b, %Y')
			%div.col-xs-6
				= link_to listing.title, listing
			%div.col-xs-3
				= listing.city
				,
				= listing.state
- else
	%p There's no post present for this category

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rubylist", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Post to classified", new_listing_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "My Listing", mylistings_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubylist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>

    <div class="container">
      <% if flash[:notice] %>
        <%= content_tag(:div, flash[:notice], class: "alert alert-success") %>
      <% end %>
      <% if flash[:alert] %>
        <%= content_tag(:div, flash[:alert], class: "alert alert-warning") %>
      <% end %>
    </div>
    
  	<div class="container">
    	<%= yield %>
    </div>
    
  </body>
</html>

app/views/listings/_form.html.haml
= simple_form_for @listing do |f|
	%div.col-md-6
		= f.input :category_id, collection: Category.all, prompt: "Select Category", label: false
		= f.input :subcategory_id, collection: Category.all, as: :grouped_select, group_label: :category_id, group_method: :subcategories

		= f.input :title, label: false, input_html: {placeholder: "Title"}
		= f.input :description, label: false, input_html: {rows:10, placeholder:"Description"}
	%div.col-md-6
		= f.input :city, label: false, input_html: {placeholder: "City"}
		= f.input :state, label: false, input_html: {placeholder: "State"}
		= f.input :zipcode, label: false, input_html: {placeholder: "zipcode"}
	%div.col-md-12
		= f.button :submit







		/ = f.input :subcategory_id, collection: Subcategory.all, prompt: "Select Subcategory"

app/views/listings/edit.html.haml
%h3 Edit Listing

= render 'form'

app/views/listings/index.html.haml
%h1 this is listing index

app/views/listings/mylistings.html.haml
- if @listings.present?
	- @listings.each do |listing|
		%div
			%div.col-xs-2
				= listing.created_at.strftime('%d %b, %Y')
			%div.col-xs-4
				= link_to listing.title, listing
			%div.col-xs-3
				= listing.city
				,
				= listing.state
			%div.col-xs-3
				%div.btn-group
					%div.btn.btn-default
						= link_to "Edit Post", edit_listing_path(listing)
					%div.btn.btn-default
						= link_to "Delete Post", listing, method: :delete
- else
	%p There's no post present for this category

app/views/listings/new.html.haml
%h1 Compose a new listing

= render 'form'

app/views/listings/search.html.haml
- if @listings.present?
	- @listings.each do |listing|
		%div.row
			%div.col-xs-2
				= listing.created_at.strftime('%d %b, %Y')
			%div.col-xs-4
				= link_to listing.title, listing
			%div.col-xs-3
				posted in
				= link_to listing.category.name, listing.category
				\/
				= link_to listing.subcategory.name, category_subcategory_path(listing.category.id, listing.subcategory.id)
			%div.col-xs-3
				= listing.city
				,
				= listing.state
- else
	%p There's no post present for this category

app/views/listings/show.html.haml
%ol.breadcrumb
	%li= link_to "Rubylist", root_path
	%li= link_to @sub.category.name, @sub.category
	%li= @sub.name

%div.page-header
	%h1
		= @listing.title
		%small
			Posted 
			= time_ago_in_words(@listing.created_at)
			ago
%p= @listing.description